#!/bin/bash
fun_trans () { 
local texto
local retorno
declare -A texto
[[ ! -e /etc/texto-adm ]] && touch /etc/texto-adm
source /etc/texto-adm
if [[ -z $(echo ${texto[$2]}) ]]; then
ENGINES=(aspell google deepl bing spell hunspell apertium yandex)
  while [[ -z $retorno ]]; do
    NUM="$(($RANDOM%${#ENGINES[@]}))"
    retorno="$(source trans -e ${ENGINES[$NUM]} -b pt:$1 "$2"|sed -e 's/[^a-z0-9 -]//ig' 2>/dev/null)"
  done
 echo "texto[$2]='$retorno'"  >> /etc/texto-adm
 echo "$retorno"
else
 echo "${texto[$2]}"
fi
}
declare -A TIMEUS
SCPdir="/etc/newadm"
SCPusr="${SCPdir}/ger-user"
MyPID="${SCPusr}/pid-adm"
[[ -e ${MyPID} ]] && source ${MyPID} || touch ${MyPID}
MyTIME="${SCPusr}/time-adm"
[[ -e ${MyTIME} ]] && source ${MyTIME} || touch ${MyTIME}
USRdatabase="/etc/ADMuser"
[[ ! -e ${USRdatabase} ]] && touch ${USRdatabase}
sort ${USRdatabase} | uniq > ${USRdatabase}tmp
mv -f ${USRdatabase}tmp ${USRdatabase}
# Funcoes Globais
msg () {
BRAN='\033[33m' && VERMELHO='\e[31m'
VERDE='\e[33m' && AMARELO='\e[33m'
AZUL='\e[33m' && MAGENTA='\e[35m'
MAG='\033[33m' && NEGRITO='\e[1m'
SEMCOR='\e[0m'
 case $1 in
  -ne)cor="${VERMELHO}${NEGRITO}" && echo -ne "${cor}${2}${SEMCOR}";;
  -ama)cor="${AMARELO}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
  -verm)cor="${AMARELO}${NEGRITO}[!] ${VERMELHO}" && echo -e "${cor}${2}${SEMCOR}";;
  -azu)cor="${MAG}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
  -verd)cor="${VERDE}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
  -bra)cor="${BRAN}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
  "-bar2"|"-bar")cor="${AZUL}======================================================" && echo -e "${SEMCOR}${cor}${SEMCOR}";;
 esac
}
# Open VPN
newclient () {
#Nome #Senha
usermod -p $(openssl passwd -1 $2) $1
  while [[ ${newfile} != @(s|S|y|Y|n|N) ]]; do
   read -p "$(fun_trans ${id} "Criar Arquivo Openvpn")? [S/N]: " -e -i S newfile
   tput cuu1 && tput dl1
  done
if [[ ${newfile} = @(s|S) ]]; then
cp /etc/openvpn/client-common.txt $HOME/$1.ovpn
echo "<key>
$(cat /etc/openvpn/client-key.pem)
</key>
<cert>
$(cat /etc/openvpn/client-cert.pem)
</cert>
<ca>
$(cat /etc/openvpn/ca.pem)
</ca>" >> $HOME/$1.ovpn
  while [[ ${ovpnauth} != @(s|S|y|Y|n|N) ]]; do
    read -p "$(fun_trans ${id} "Colocar Autenticacao de Usuario no Arquivo")? [S/N]: " -e -i S ovpnauth
    tput cuu1 && tput dl1
  done
  [[ ${ovpnauth} = @(n|N) ]] && sed -i "s;auth-user-pass;<auth-user-pass>\n$1\n$2\n</auth-user-pass>;g" $HOME/$1.ovpn
  cd $HOME
  zip ./$1.zip ./$1.ovpn > /dev/null 2>&1
  rm ./$1.ovpn > /dev/null 2>&1
  echo -e "\033[1;31m$(fun_trans ${id} "Arquivo Criado em"): ($HOME/$1.zip)"
 fi
}
add_user () {
#nome senha Dias limite
[[ $(cat /etc/passwd |grep $1: |grep -vi [a-z]$1 |grep -v [0-9]$1 > /dev/null) ]] && return 1
valid=$(date '+%C%y-%m-%d' -d " +$3 days") && datexp=$(date "+%F" -d " + $3 days")
useradd -M -s /bin/false $1 -e ${valid} > /dev/null 2>&1 || return 1
(echo $2; echo $2)|passwd $1 2>/dev/null || {
    userdel --force $1
    return 1
    }
[[ -e ${USRdatabase} ]] && {
   newbase=$(cat ${USRdatabase}|grep -w -v "$1")
   echo "$1|$2|${datexp}|$4" > ${USRdatabase}
   for value in `echo ${newbase}`; do
   echo $value >> ${USRdatabase}
   done
   } || echo "$1|$2|${datexp}|$4" > ${USRdatabase}
}
renew_user_fun () {
#nome dias
datexp=$(date "+%F" -d " + $2 days") && valid=$(date '+%C%y-%m-%d' -d " + $2 days")
chage -E $valid $1 2> /dev/null || return 1
[[ -e ${USRdatabase} ]] && {
   newbase=$(cat ${USRdatabase}|grep -w -v "$1")
   useredit=$(cat ${USRdatabase}|grep -w "$1")
   pass=$(echo $useredit|cut -d'|' -f2)
   limit=$(echo $useredit|cut -d'|' -f4)
   echo "$1|$pass|${datexp}|$limit" > ${USRdatabase}
   for value in `echo ${newbase}`; do
   echo $value >> ${USRdatabase}
   done
   }
}
edit_user_fun () {
#nome senha dias limite
(echo "$2" ; echo "$2" ) |passwd $1 > /dev/null 2>&1 || return 1
datexp=$(date "+%F" -d " + $3 days") && valid=$(date '+%C%y-%m-%d' -d " + $3 days")
chage -E $valid $1 2> /dev/null || return 1
[[ -e ${USRdatabase} ]] && {
   newbase=$(cat ${USRdatabase}|grep -w -v "$1")
   echo "$1|$2|${datexp}|$4" > ${USRdatabase}
   for value in `echo ${newbase}`; do
   echo $value >> ${USRdatabase}
   done
   } || echo "$1|$2|${datexp}|$4" > ${USRdatabase}
}
rm_user () {
#nome
userdel --force "$1" &>/dev/null || return 1
[[ -e ${USRdatabase} ]] && {
   newbase=$(cat ${USRdatabase}|grep -w -v "$1")
   for value in `echo ${newbase}`; do
   echo $value >> ${USRdatabase}
   done
   }
}
mostrar_usuarios () {
for u in `awk -F : '$3 > 900 { print $1 }' /etc/passwd | grep -v "nobody" |grep -vi polkitd |grep -vi system-`; do
echo "$u"
done
}
dropbear_pids () {
unset pids
port_dropbear=`ps aux | grep dropbear | awk NR==1 | awk '{print $17;}'`
log=/var/log/auth.log
loginsukses='Password auth succeeded'
[[ -z $port_dropbear ]] && return 1
for port in `echo $port_dropbear`; do
 for pidx in $(ps ax |grep dropbear |grep "$port" |awk -F" " '{print $1}'); do
  pids="${pids}$pidx\n"
 done
done
for pid in `echo -e "$pids"`; do
  pidlogs=`grep $pid $log |grep "$loginsukses" |awk -F" " '{print $3}'`
  i=0
    for pidend in $pidlogs; do
    let i++
    done
    if [[ $pidend ]]; then
    login=$(grep $pid $log |grep "$pidend" |grep "$loginsukses")
    PID=$pid
    user=`echo $login |awk -F" " '{print $10}' | sed -r "s/'//g"`
    waktu=$(echo $login |awk -F" " '{print $2"-"$1,$3}')
    [[ -z $user ]] && continue
    echo "$user|$PID|$waktu"
    fi
done
}
openvpn_pids () {
#nome|#loguin|#rcv|#snd|#time
  byte () {
   while read B dummy; do
   [[ "$B" -lt 1024 ]] && echo "${B} bytes" && break
   KB=$(((B+512)/1024))
   [[ "$KB" -lt 1024 ]] && echo "${KB} Kb" && break
   MB=$(((KB+512)/1024))
   [[ "$MB" -lt 1024 ]] && echo "${MB} Mb" && break
   GB=$(((MB+512)/1024))
   [[ "$GB" -lt 1024 ]] && echo "${GB} Gb" && break
   echo $(((GB+512)/1024)) terabytes
   done
   }
for user in $(mostrar_usuarios); do
user="$(echo $user|sed -e 's/[^a-z0-9 -]//ig')"
[[ ! $(sed -n "/^${user},/p" /etc/openvpn/openvpn-status.log) ]] && continue
i=0
unset RECIVED
unset SEND
unset HOUR
 while read line; do
 IDLOCAL=$(echo ${line}|cut -d',' -f2)
 RECIVED+="$(echo ${line}|cut -d',' -f3)+"
 SEND+="$(echo ${line}|cut -d',' -f4)+"
 DATESEC=$(date +%s --date="$(echo ${line}|cut -d',' -f5|cut -d' ' -f1,2,3,4)")
 TIMEON="$(($(date +%s)-${DATESEC}))"
  MIN=$(($TIMEON/60)) && SEC=$(($TIMEON-$MIN*60)) && HOR=$(($MIN/60)) && MIN=$(($MIN-$HOR*60))
  HOUR+="${HOR}h:${MIN}m:${SEC}s\n"
  let i++
 done <<< "$(sed -n "/^${user},/p" /etc/openvpn/openvpn-status.log)"
RECIVED=$(echo $(echo ${RECIVED}0|bc)|byte)
SEND=$(echo $(echo ${SEND}0|bc)|byte)
HOUR=$(echo -e $HOUR|sort -n|tail -1)
echo -e "$user|$i|$RECIVED|$SEND|$HOUR"
done
}
err_fun () {
     case $1 in
     [1-3]|14)
     [[ $1 = 1 ]] && msg -verm "$(fun_trans ${id} "Usuario Nulo")"
     [[ $1 = 2 ]] && msg -verm "$(fun_trans ${id} "Usuario Com Nome Muito Curto")"
     [[ $1 = 3 ]] && msg -verm "$(fun_trans ${id} "Usuario Com Nome Muito Grande")"
     [[ $1 = 14 ]] && msg -verm "$(fun_trans ${id} "Usuario Ja Existe")"
     sleep 2s
     tput cuu1 && tput dl1
     tput cuu1 && tput dl1
     ;;
     [4-6])
     [[ $1 = 4 ]] && msg -verm "$(fun_trans ${id} "Senha Nula")"
     [[ $1 = 5 ]] && msg -verm "$(fun_trans ${id} "Senha Muito Curta")"
     [[ $1 = 6 ]] && msg -verm "$(fun_trans ${id} "Senha Muito Grande")"
     sleep 2s
     tput cuu1 && tput dl1
     tput cuu1 && tput dl1
     tput cuu1 && tput dl1
     ;;
     [7-9])
     [[ $1 = 7 ]] && msg -verm "$(fun_trans ${id} "Duracao Nula")"
     [[ $1 = 8 ]] && msg -verm "$(fun_trans ${id} "Duracao invalida utilize numeros")"
     [[ $1 = 9 ]] && msg -verm "$(fun_trans ${id} "Duracao maxima e de um ano")"
     sleep 2s
     tput cuu1 && tput dl1
     tput cuu1 && tput dl1
     tput cuu1 && tput dl1
     tput cuu1 && tput dl1
     ;;
     1[1-3])
     [[ $1 = 11 ]] && msg -verm "$(fun_trans ${id} "Limite Nulo")"
     [[ $1 = 12 ]] && msg -verm "$(fun_trans ${id} "Limite invalido utilize numeros")"
     [[ $1 = 13 ]] && msg -verm "$(fun_trans ${id} "Limite maximo e de 999")"
     sleep 2s
     tput cuu1 && tput dl1
     tput cuu1 && tput dl1
     tput cuu1 && tput dl1
     tput cuu1 && tput dl1
     tput cuu1 && tput dl1
     ;;
     esac
}
new_user () {
usuarios_ativos=($(mostrar_usuarios))
if [[ -z ${usuarios_ativos[@]} ]]; then
msg -verm "$(fun_trans ${id} "Nenhum Usuario Cadastrado")"
msg -bar
else
msg -ama "$(fun_trans ${id} "Usuarios Atualmente Ativos no Servidor")"
msg -bar
for us in $(echo ${usuarios_ativos[@]}); do
msg -ne "User: " && echo "${us}"
done
msg -bar
fi
while [[ $err != "true" ]]; do
     msg -ne "$(fun_trans ${id} "Nome Do Novo Usuario")"
     read -p ": " nomeuser
     nomeuser="$(echo $nomeuser|sed -e 's/[^a-z0-9 -]//ig')"
     if [[ -z $nomeuser ]]; then
     err_fun 1 && continue
     elif [[ "${#nomeuser}" -lt "4" ]]; then
     err_fun 2 && continue
     elif [[ "${#nomeuser}" -gt "24" ]]; then
     err_fun 3 && continue
     elif [[ "$(echo ${usuarios_ativos[@]}|grep -w "$nomeuser")" ]]; then
     err_fun 14 && continue
     fi    
     msg -ne "$(fun_trans ${id} "Senha Novo Usuario")"
     read -p ": " senhauser
     if [[ -z $senhauser ]]; then
     err_fun 4 && continue
     elif [[ "${#senhauser}" -lt "6" ]]; then
     err_fun 5 && continue
     elif [[ "${#senhauser}" -gt "20" ]]; then
     err_fun 6 && continue
     fi
     [[ $? = "0" ]]
     msg -ne "$(fun_trans ${id} "Tempo de Duracao do Novo Usuario")"
     read -p ": " diasuser
     if [[ -z "$diasuser" ]]; then
     err_fun 7 && continue
     elif [[ "$diasuser" != +([0-9]) ]]; then
     err_fun 8 && continue
     elif [[ "$diasuser" -gt "360" ]]; then
     err_fun 9 && continue
     fi     
     msg -ne "$(fun_trans ${id} "Limite de Conexao do Novo Usuario")"
     read -p ": " limiteuser
     if [[ -z "$limiteuser" ]]; then
     err_fun 11 && continue
     elif [[ "$limiteuser" != +([0-9]) ]]; then
     err_fun 12 && continue
     elif [[ "$limiteuser" -gt "999" ]]; then
     err_fun 13 && continue
     fi
     tput cuu1 && tput dl1
     tput cuu1 && tput dl1
     tput cuu1 && tput dl1
     tput cuu1 && tput dl1
     msg -ne "$(fun_trans ${id} "IP do Servidor"): " && echo -e "$(meu_ip)"
     msg -ne "$(fun_trans ${id} "Usuario"): " && echo -e "$nomeuser"
     msg -ne "$(fun_trans ${id} "Senha"): " && echo -e "$senhauser"
     msg -ne "$(fun_trans ${id} "Dias de Duracao"): " && echo -e "$diasuser"
     msg -ne "$(fun_trans ${id} "Data de Expiracao"): " && echo -e "$(date "+%F" -d " + $diasuser days")"
     msg -ne "$(fun_trans ${id} "Limite de Conexao"): " && echo -e "$limiteuser"
     err=true
done
msg -bar
add_user "${nomeuser}" "${senhauser}" "${diasuser}" "${limiteuser}" && msg -ama "$(fun_trans ${id} "Usuario Criado Com Sucesso")" || msg -verm "$(fun_trans ${id} "Erro, Usuario nao criado")"
[[ $(dpkg --get-selections|grep -w "openvpn"|head -1) ]] && [[ -e /etc/openvpn/openvpn-status.log ]] && newclient "$nomeuser" "$senhauser"
msg -bar
}
meu_ip () {
if [[ -e /etc/MEUIPADM ]]; then
echo "$(cat /etc/MEUIPADM)"
else
MEU_IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
MEU_IP2=$(wget -qO- ipv4.icanhazip.com)
[[ "$MEU_IP" != "$MEU_IP2" ]] && echo "$MEU_IP2" || echo "$MEU_IP"
echo "$MEU_IP2" > /etc/MEUIPADM
fi
}
remove_user () {
usuarios_ativos=($(mostrar_usuarios))
if [[ -z ${usuarios_ativos[@]} ]]; then
msg -verm "$(fun_trans ${id} "Nenhum Usuario Cadastrado")"
msg -bar
return 1
else
msg -ama "$(fun_trans ${id} "Usuarios Atualmente Ativos no Servidor")"
msg -bar
i=0
for us in $(echo ${usuarios_ativos[@]}); do
msg -ne "[$i] ->" && echo -e "\033[1;33m ${us}"
let i++
done
msg -bar
fi
msg -ama "$(fun_trans ${id} "Digite ou Selecione um Usuario")"
msg -bar
unset selection
while [[ ${selection} = "" ]]; do
echo -ne "\033[1;37m${txt[8]}: " && read selection
tput cuu1 && tput dl1
done
if [[ ! $(echo "${selection}" | egrep '[^0-9]') ]]; then
usuario_del="${usuarios_ativos[$selection]}"
else
usuario_del="$selection"
fi
[[ -z $usuario_del ]] && {
     msg -verm "$(fun_trans ${id} "Erro, Usuario Invalido")"
     msg -bar
     return 1
     }
[[ ! $(echo ${usuarios_ativos[@]}|grep -w "$usuario_del") ]] && {
     msg -verm "$(fun_trans ${id} "Erro, Usuario Invalido")"
     msg -bar
     return 1
     }
msg -ne "$(fun_trans ${id} "Usuario Selecionado"): " && echo -ne "$usuario_del"
rm_user "$usuario_del" && msg -verd " [$(fun_trans ${id} "Removido")]" || msg -verm " [$(fun_trans ${id} "Nao Removido")]"
msg -bar
}
renew_user () {
usuarios_ativos=($(mostrar_usuarios))
if [[ -z ${usuarios_ativos[@]} ]]; then
msg -verm "$(fun_trans ${id} "Nenhum Usuario Cadastrado")"
msg -bar
return 1
else
msg -ama "$(fun_trans ${id} "Usuarios Atualmente Ativos no Servidor")"
msg -bar
i=0
for us in $(echo ${usuarios_ativos[@]}); do
msg -ne "[$i] ->" && echo -e "\033[1;33m ${us}"
let i++
done
msg -bar
fi
msg -ama "$(fun_trans ${id} "Digite ou Selecione um Usuario")"
msg -bar
unset selection
while [[ ${selection} = "" ]]; do
echo -ne "\033[1;37m${txt[8]}: " && read selection
tput cuu1
tput dl1
done
if [[ ! $(echo "${selection}" | egrep '[^0-9]') ]]; then
useredit="${usuarios_ativos[$selection]}"
else
useredit="$selection"
fi
[[ -z $useredit ]] && {
     msg -verm "$(fun_trans ${id} "Erro, Usuario Invalido")"
     msg -bar
     return 1
     }
[[ ! $(echo ${usuarios_ativos[@]}|grep -w "$useredit") ]] && {
     msg -verm "$(fun_trans ${id} "Erro, Usuario Invalido")"
     msg -bar
     return 1
     }
while [[ $err != "true" ]]; do
     msg -ne "$(fun_trans ${id} "Novo Tempo de Duracao de"): $useredit"
     read -p ": " diasuser
     if [[ -z "$diasuser" ]]; then
     echo -e '\n\n\n'
     err_fun 7 && continue
     elif [[ "$diasuser" != +([0-9]) ]]; then
     echo -e '\n\n\n'
     err_fun 8 && continue
     elif [[ "$diasuser" -gt "360" ]]; then
     echo -e '\n\n\n'
     err_fun 9 && continue
     fi
     err=true
done
msg -bar
renew_user_fun "${useredit}" "${diasuser}" && msg -ama "$(fun_trans ${id} "Usuario Modificado Com Sucesso")" || msg -verm "$(fun_trans ${id} "Erro, Usuario nao Modificado")"
msg -bar
}
edit_user () {
usuarios_ativos=($(mostrar_usuarios))
if [[ -z ${usuarios_ativos[@]} ]]; then
msg -verm "$(fun_trans ${id} "Nenhum Usuario Cadastrado")"
msg -bar
return 1
else
msg -ama "$(fun_trans ${id} "Usuarios Atualmente Ativos no Servidor")"
msg -bar
i=0
for us in $(echo ${usuarios_ativos[@]}); do
msg -ne "[$i] ->" && echo -e "\033[1;33m ${us}"
let i++
done
msg -bar
fi
msg -ama "$(fun_trans ${id} "Digite ou Selecione um Usuario")"
msg -bar
unset selection
while [[ ${selection} = "" ]]; do
echo -ne "\033[1;37m${txt[8]}: " && read selection
tput cuu1
tput dl1
done
if [[ ! $(echo "${selection}" | egrep '[^0-9]') ]]; then
useredit="${usuarios_ativos[$selection]}"
else
useredit="$selection"
fi
[[ -z $useredit ]] && {
     msg -verm "$(fun_trans ${id} "Erro, Usuario Invalido")"
     msg -bar
     return 1
     }
[[ ! $(echo ${usuarios_ativos[@]}|grep -w "$useredit") ]] && {
     msg -verm "$(fun_trans ${id} "Erro, Usuario Invalido")"
     msg -bar
     return 1
     }
while [[ $err != "true" ]]; do
msg -ne "$(fun_trans ${id} "Usuario Selecionado"): " && echo -e "$useredit"
     msg -ne "$(fun_trans ${id} "Nova Senha de"): $useredit"
     read -p ": " senhauser
     if [[ -z "$senhauser" ]]; then
     err_fun 4 && continue
     elif [[ "${#senhauser}" -lt "6" ]]; then
     err_fun 5 && continue
     elif [[ "${#senhauser}" -gt "20" ]]; then
     err_fun 6 && continue
     fi
     [[ $? = "0" ]]
     msg -ne "$(fun_trans ${id} "Dias de Duracao de"): $useredit"
     read -p ": " diasuser
     if [[ -z "$diasuser" ]]; then
     err_fun 7 && continue
     elif [[ "$diasuser" != +([0-9]) ]]; then
     err_fun 8 && continue
     elif [[ "$diasuser" -gt "360" ]]; then
     err_fun 9 && continue
     fi
     msg -ne "$(fun_trans ${id} "Novo Limite de Conexao de"): $useredit"
     read -p ": " limiteuser
     if [[ -z "$limiteuser" ]]; then
     err_fun 11 && continue
     elif [[ "$limiteuser" != +([0-9]) ]]; then
     err_fun 12 && continue
     elif [[ "$limiteuser" -gt "999" ]]; then
     err_fun 13 && continue
     fi
     tput cuu1 && tput dl1
     tput cuu1 && tput dl1
     tput cuu1 && tput dl1
     tput cuu1 && tput dl1
     msg -ne "$(fun_trans ${id} "Usuario"): " && echo -e "$useredit"
     msg -ne "$(fun_trans ${id} "Senha"): " && echo -e "$senhauser"
     msg -ne "$(fun_trans ${id} "Dias de Duracao"): " && echo -e "$diasuser"
     msg -ne "$(fun_trans ${id} "Data de Expiracao"): " && echo -e "$(date "+%F" -d " + $diasuser days")"
     msg -ne "$(fun_trans ${id} "Limite de Conexao"): " && echo -e "$limiteuser"
     err=true
done
msg -bar
edit_user_fun "${useredit}" "${senhauser}" "${diasuser}" "${limiteuser}" && msg -ama "$(fun_trans ${id} "Usuario Modificado Com Sucesso")" || msg -verm "$(fun_trans ${id} "Erro, Usuario nao Modificado")"
msg -bar
}
detail_user () {
tput cuu1 && tput dl1
msg -bar2
red=$(tput setaf 1)
gren=$(tput setaf 2)
yellow=$(tput setaf 3)
if [[ ! -e "${USRdatabase}" ]]; then
msg -verm "$(fun_trans ${id} "Nao Foi Identificado uma Database Com Usuarios")"
msg -verm "$(fun_trans ${id} "Os Usuarios a Seguir Nao Contem Nenhuma Informacao")"
msg -bar2
fi
txtvar=$(printf '%-16s' "USER")
txtvar+=$(printf '%-16s' "PASS")
txtvar+=$(printf '%-16s' "DATE")
txtvar+=$(printf '%-6s' "LIMIT")
echo -e "\033[1;33m${txtvar}"
msg -bar2
VPSsec=$(date +%s)
while read user; do
unset txtvar
data_user=$(chage -l "$user" |grep -i co |awk -F ":" '{print $2}')
txtvar=$(printf '%-21s' "${yellow}$user")
if [[ -e "${USRdatabase}" ]]; then
  if [[ $(cat ${USRdatabase}|grep -w "${user}") ]]; then
    txtvar+="$(printf '%-21s' "${yellow}$(cat ${USRdatabase}|grep -w "${user}"|cut -d'|' -f2)")"
    DateExp="$(cat ${USRdatabase}|grep -w "${user}"|cut -d'|' -f3)"
    DataSec=$(date +%s --date="$DateExp")
    if [[ "$VPSsec" -gt "$DataSec" ]]; then    
    EXPTIME="${red}[Exp]"
    else
    EXPTIME="${gren}[$(($(($DataSec - $VPSsec)) / 86400))]"
    fi
    txtvar+="$(printf '%-26s' "${yellow}${DateExp}${EXPTIME}")"
    txtvar+="$(printf '%-11s' "${yellow}$(cat ${USRdatabase}|grep -w "${user}"|cut -d'|' -f4)")"
    else
    txtvar+="$(printf '%-21s' "${red}???")"
    txtvar+="$(printf '%-21s' "${red}???")"
    txtvar+="$(printf '%-11s' "${red}???")"
  fi
fi
echo -e "$txtvar"
done <<< "$(mostrar_usuarios)"
msg -bar2
}
monit_user () {
yellow=$(tput setaf 3)
gren=$(tput setaf 2)
msg -verm "$(fun_trans ${id} "Monitor de Conexoes de Usuarios")"
msg -bar
txtvar=$(printf '%-13s' "USER")
txtvar+=$(printf '%-19s' "CONNECTION")
txtvar+=$(printf '%-16s' "TIME/ON")
echo -e "\033[1;33m${txtvar}"
msg -bar
while read user; do
 _=$(
PID="0+"
[[ $(dpkg --get-selections|grep -w "openssh"|head -1) ]] && PID+="$(ps aux|grep -v grep|grep sshd|grep -w "$user"|grep -v root|wc -l)+"
[[ $(dpkg --get-selections|grep -w "dropbear"|head -1) ]] && PID+="$(dropbear_pids|grep -w "${user}"|wc -l)+"
[[ $(dpkg --get-selections|grep -w "openvpn"|head -1) ]] && [[ -e /etc/openvpn/openvpn-status.log ]] && [[ $(openvpn_pids|grep -w "$user"|cut -d'|' -f2) ]] && PID+="$(openvpn_pids|grep -w "$user"|cut -d'|' -f2)+"
PID+="0"
TIMEON="${TIMEUS[$user]}"
[[ -z $TIMEON ]] && TIMEON=0
MIN=$(($TIMEON/60))
SEC=$(($TIMEON-$MIN*60))
HOR=$(($MIN/60))
MIN=$(($MIN-$HOR*60))
HOUR="${HOR}h:${MIN}m:${SEC}s"
[[ -z $(cat ${USRdatabase}|grep -w "${user}") ]] && MAXUSER="?" || MAXUSER="$(cat ${USRdatabase}|grep -w "${user}"|cut -d'|' -f4)"
[[ $(echo $PID|bc) -gt 0 ]] && user="$user [\033[1;32mON\033[0m${yellow}]" || user="$user [\033[1;31mOFF\033[0m${yellow}]"
TOTALPID="$(echo $PID|bc)/$MAXUSER"
 while [[ ${#user} -lt 45 ]]; do
 user=$user" "
 done
 while [[ ${#TOTALPID} -lt 13 ]]; do
 TOTALPID=$TOTALPID" "
 done
 while [[ ${#HOUR} -lt 8 ]]; do
 HOUR=$HOUR" "
 done
echo -e "${yellow}$user $TOTALPID $HOUR" >&2
) &
pid=$!
sleep 0.5s
done <<< "$(mostrar_usuarios)"
while [[ -d /proc/$pid ]]; do
sleep 1s
done
msg -bar
}
user_demo () {
/etc/newadm/USUARIO-DEMO
tput cuu1 && tput dl1
}
rm_vencidos () {
red=$(tput setaf 1)
gren=$(tput setaf 2)
yellow=$(tput setaf 3)
txtvar=$(printf '%-25s' "USER")
txtvar+=$(printf '%-20s' "VALID")
echo -e "\033[1;33m${txtvar}"
msg -bar
expired="${red}$(fun_trans ${id} "Expirado")"
valid="${gren}$(fun_trans ${id} "Usuario Valido")"
never="${yellow}$(fun_trans ${id} "Usuario Ilimitado")"
removido="${red}$(fun_trans ${id} "Removido")"
DataVPS=$(date +%s)
while read user; do
DataUser=$(chage -l "${user}" |grep -i co|awk -F ":" '{print $2}')
usr=$user
 while [[ ${#usr} -lt 20 ]]; do
 usr=$usr" "
 done
[[ "$DataUser" = " never" ]] && {
   echo -e "${yellow}$usr $never"
   continue
   }
DataSEC=$(date +%s --date="$DataUser")
if [[ "$DataSEC" -lt "$DataVPS" ]]; then
echo -ne "${yellow}$usr $expired"
rm_user "$user" && echo -e "($removido)"
else
echo -e "${yellow}$usr $valid"
fi
done <<< "$(mostrar_usuarios)"
msg -bar
}
verif_fun () {
    declare -A conexao
    declare -A limite
    declare -A TIMEUS 
    while true; do
    sleep 1s # Aguarda o Inicio do Processo
    [[ -e ${MyTIME} ]] && source ${MyTIME}
    TimeNOW=$(date +%s)
    unset EXPIRED
    unset ONLINES
     while read user; do
     DataUser=$(chage -l "${user}" |grep -i co|awk -F ":" '{print $2}')
     usr=$user
     [[ ! -z "$(echo $DataUser|grep never)" ]] && continue
     DataSEC=$(date +%s --date="$DataUser")
     if [[ "$DataSEC" -lt "$TimeNOW" ]]; then
     EXPIRED="1+"
     usermod -L $user
     fi
     done <<< "$(mostrar_usuarios)"    
     while read user; do
     PID="0+"
     [[ ! $(echo $(mostrar_usuarios)|grep -w "$user") ]] && continue
     [[ $(dpkg --get-selections|grep -w "openssh"|head -1) ]] && PID+="$(ps aux|grep -v grep|grep sshd|grep -w "$user"|grep -v root|wc -l 2>/dev/null)+"
     [[ $(dpkg --get-selections|grep -w "dropbear"|head -1) ]] && PID+="$(dropbear_pids|grep -w "$user"|wc -l 2>/dev/null)+"
     [[ $(dpkg --get-selections|grep -w "openvpn"|head -1) ]] && [[ -e /etc/openvpn/openvpn-status.log ]] && [[ $(openvpn_pids|grep -w "$user"|cut -d'|' -f2) ]] && PID+="$(openvpn_pids|grep -w "$user"|cut -d'|' -f2)+"
     TOTALPID=$(echo ${PID}0|bc)
     [[ "${TOTALPID}" = "0" ]] && {
     usermod -U $user
     continue
     }
     ONLINES+="${TOTALPID}+"
     conexao[$user]="${TOTALPID}"
     [[ -z "${TIMEUS[$user]}" ]] && TIMEUS[$user]=0
     [[ "${TIMEUS[$user]}" != +([0-9]) ]] && TIMEUS[$user]=0
     # VAR COMP $(($(date +%s)-$TimeNOW))
     TIMEUS[$user]="$((1+${TIMEUS[$user]}))"
     VARS="$(cat ${MyTIME}|grep -w -v "$user")"
     echo "TIMEUS[$user]='${TIMEUS[$user]}'" > ${MyTIME}
     for variavel in $(echo ${VARS}); do
     echo "${variavel}" >> ${MyTIME}
     done 
     limite[$user]="$(cat ${USRdatabase}|grep -w "${user}"|cut -d'|' -f4)"
     [[ -z "${limite[$user]}" ]] && continue
     [[ "${limite[$user]}" != +([0-9]) ]] && continue
     [[ "${conexao[$user]}" -le "${limite[$user]}" ]] && {
     usermod -U $user
     continue
     } || {
     NUNBER_KILL=$((${conexao[$user]}-${limite[$user]}))
     PIDS_KILL=$(ps x|grep [[:space:]]$user[[:space:]]|grep -v grep|grep -v pts|awk '{print $1}'|tail -n${NUNBER_KILL})
     for PIDEND in `${PIDS_KILL}`; do
     kill -9 ${PIDEND}
     done
     usermod -L $user
     }
    done <<< "$(mostrar_usuarios)"
    ONLINES+="0"
    EXPIRED+="0"
    echo $ONLINES|bc > ${SCPdir}/USRonlines
    echo $EXPIRED|bc > ${SCPdir}/USRexpired
    done
}
backup_fun () {
msg -ama "$(fun_trans ${id} "FERRAMENTA DE BACKUP DE USUARIOS")"
msg -bar
echo -ne "\033[1;32m [1] > " && msg -azu "$(fun_trans ${id} "CRIAR BACKUP")"
echo -ne "\033[1;32m [2] > " && msg -azu "$(fun_trans ${id} "RESTAURAR BACKUP")"
msg -bar
unset selection
while [[ ${selection} != @([1-2]) ]]; do
echo -ne "\033[1;37m${txt[8]}: " && read selection
tput cuu1 && tput dl1
done
case ${selection} in
1)
cp ${USRdatabase} $HOME/Backup-adm
msg -azu "$(fun_trans ${id} "Procedimento Feito")"
echo -e "\033[1;31mBACKUP > [\033[1;32m$HOME/Backup-adm\033[1;31m]"
;;
2)
while [[ ! -e ${dirbackup} ]]; do
echo -ne "\033[1;37m$(fun_trans ${id} "Digite o Local Do Backup"): " && read dirbackup
tput cuu1 && tput dl1
done
VPSsec=$(date +%s)
while read line; do
nome=$(echo ${line}|cut -d'|' -f1)
[[ $(echo $(mostrar_usuarios)|grep -w "$nome") ]] && {
  msg -verm "$nome [ERROR]"
  continue
  }
senha=$(echo ${line}|cut -d'|' -f2)
DateExp=$(echo ${line}|cut -d'|' -f3)
DataSec=$(date +%s --date="$DateExp")
[[ "$VPSsec" -lt "$DataSec" ]] && dias="$(($(($DataSec - $VPSsec)) / 86400))" || dias="30"
limite=$(echo ${line}|cut -d'|' -f4)
add_user "$nome" "$senha" "$dias" "$limite" && msg -verd "$nome [OK]" || msg -verm "$nome [ERROR]"
done < ${dirbackup}
;;
esac
msg -bar
}
verif_funx () {
PIDVRF="$(ps aux|grep "${SCPusr}/usercodes verificar"|grep -v grep|awk '{print $2}')"
if [[ -z $PIDVRF ]]; then
cd ${SCPusr}
screen -dmS very ${SCPusr}/usercodes verificar
else
for pid in $(echo $PIDVRF); do
kill -9 $pid &>/dev/null
done
for USR in $(mostrar_usuarios); do
usermod -U $USR
done
[[ -e ${SCPdir}/USRonlines ]] && rm ${SCPdir}/USRonlines
[[ -e ${SCPdir}/USRexpired ]] && rm ${SCPdir}/USRexpired
fi
}
baner_fun () {
local2="/etc/dropbear/banner"
chk=$(cat /etc/ssh/sshd_config | grep Banner)
if [ "$(echo "$chk" | grep -v "#Banner" | grep Banner)" != "" ]; then
local=$(echo "$chk" |grep -v "#Banner" | grep Banner | awk '{print $2}')
 else
echo "Banner /etc/bannerssh" >> /etc/ssh/sshd_config
local="/etc/bannerssh"
fi
msg -verd "$(fun_trans ${id} "instalador do banner")"
msg -bar
msg -ne "$(fun_trans ${id} "digite a mensagem principal do banner"): " && read ban_ner
echo -e " \033[1;32m[1] >\033[1;32m $(fun_trans ${id} "Verde")"
echo -e " \033[1;32m[2] >\033[1;31m $(fun_trans ${id} "Vermelho")"
echo -e " \033[1;32m[3] >\033[1;34m $(fun_trans ${id} "Azul")"
echo -e " \033[1;32m[4] >\033[1;33m $(fun_trans ${id} "Amarelo")"
echo -e " \033[1;32m[5] >\033[1;35m $(fun_trans ${id} "Roxo")"
msg -ne "$(fun_trans ${id} "Perfeito Agora a Cor"): " && read ban_ner_cor
echo '<h1><font>=============================</font></h1>' > $local
if [[ "$ban_ner_cor" = "1" ]]; then
echo '<h1><font color="green">' >> $local
elif [[ "$ban_ner_cor" = "2" ]]; then
echo '<h1><font color="red">' >> $local
elif [[ "$ban_ner_cor" = "3" ]]; then
echo '<h1><font color="blue">' >> $local
elif [[ "$ban_ner_cor" = "4" ]]; then
echo '<h1><font color="yellow">' >> $local
elif [[ "$ban_ner_cor" = "5" ]]; then
echo '<h1><font color="purple">' >> $local
else
echo '<h1><font color="blue">' >> $local
fi
echo "$ban_ner" >> $local
echo '</font></h1>' >> $local
echo '<h1><font>=============================</font></h1>' >> $local
txt_font () {
msg -ne "$(fun_trans ${id} "digite a mensagem secundaria"): " && read ban_ner2
echo -e " \033[1;32m[1] >\033[1;32m $(fun_trans ${id} "Verde")"
echo -e " \033[1;32m[2] >\033[1;31m $(fun_trans ${id} "Vermelho")"
echo -e " \033[1;32m[3] >\033[1;34m $(fun_trans ${id} "Azul")"
echo -e " \033[1;32m[4] >\033[1;33m $(fun_trans ${id} "Amarelo")"
echo -e " \033[1;32m[5] >\033[1;35m $(fun_trans ${id} "Roxo")"
msg -ne "$(fun_trans ${id} "Perfeito Agora a Cor"): " && read ban_ner2_cor
if [ "$ban_ner2_cor" = "1" ]; then
echo '<h6><font color="green">' >> $local
elif [ "$ban_ner2_cor" = "2" ]; then
echo '<h6><font color="red">' >> $local
elif [ "$ban_ner2_cor" = "3" ]; then
echo '<h6><font color="blue">' >> $local
elif [ "$ban_ner2_cor" = "4" ]; then
echo '<h6><font color="yellow">' >> $local
elif [ "$ban_ner2_cor" = "5" ]; then
echo '<h6><font color="purple">' >> $local
else
echo '<h6><font color="red">' >> $local
fi
echo "$ban_ner2" >> $local
echo "</h6></font>" >> $local
}
while true; do
msg -ne "$(fun_trans ${id} "Adicionar Mensagem Secundaria")? [S/N]: " && read sin_nao
if [[ "$sin_nao" = @(s|S|y|Y) ]]; then
txt_font
elif [[ "$sin_nao" = @(n|N) ]]; then
break
fi
done
#echo '</h8><font color="purple">GOLDEN ADM PRO by @DEADSHOT593</font></h8>' >> $local
#echo '<h1><font>=============================</font></h1>' >> $local
if [[ -e "$local2" ]]; then
rm $local2  > /dev/null 2>&1
cp $local $local2 > /dev/null 2>&1
fi
msg -bar && msg -verd "$(fun_trans ${id} "Banner Adicionado Com Sucesso")" && msg -bar
service ssh restart > /dev/null 2>&1 &
service sshd restart > /dev/null 2>&1 & 
service dropbear restart > /dev/null 2>&1 &
}
# Execução
textos_fun () {
id="$1"
[[ -e /tmp/txt ]] && {
rm /tmp/txt && touch /tmp/txt
} || touch /tmp/txt
echo "txt[1]='$(fun_trans ${id} "CRIAR NOVO USUARIO")'" >> /tmp/txt &
echo "txt[2]='$(fun_trans ${id} "REMOVER USUARIO")'" >> /tmp/txt &
echo "txt[3]='$(fun_trans ${id} "EDITAR USUARIO")'" >> /tmp/txt &
echo "txt[4]='$(fun_trans ${id} "DETALHES DE TODOS USUARIOS")'" >> /tmp/txt &
echo "txt[5]='$(fun_trans ${id} "MONITORAR USUARIOS CONECTADOS")'" >> /tmp/txt &
echo "txt[6]='$(fun_trans ${id} "ELIMINAR USUARIOS VENCIDOS")'" >> /tmp/txt &
echo "txt[7]='$(fun_trans ${id} "MENU GERENCIAMENTO DE USUARIOS")'" >> /tmp/txt &
echo "txt[8]='$(fun_trans ${id} "Selecione A Opcao")'" >> /tmp/txt &
echo "txt[9]='$(fun_trans ${id} "BACKUP USUARIOS")'" >> /tmp/txt &
echo "txt[10]='$(fun_trans ${id} "VERIFICACOES")'" >> /tmp/txt &
echo "txt[11]='$(fun_trans ${id} "VOLTAR")'" >> /tmp/txt &
echo "txt[12]='$(fun_trans ${id} "BANNER SSH")'" >> /tmp/txt &
echo "txt[13]='$(fun_trans ${id} "RENOVAR USUARIO")'" >> /tmp/txt &
while [[ ! -e /tmp/txt || $(cat /tmp/txt|wc -l) -lt "13"  ]]; do
continue
done
source /tmp/txt && rm /tmp/txt
}
if [[ "$1" = "verificar" ]]; then
verif_fun
fi
VERY="$(ps aux|grep "${SCPusr}/usercodes verificar"| grep -v grep)"
[[ -z ${VERY} ]] && verificar="\033[1;31mOff" || verificar="\033[1;32mOn"
[[ -z $1 ]] && textos_fun pt || textos_fun $1
msg -ama "${txt[7]}"
msg -bar
echo -ne "\033[33m [1] > " && msg -azu "${txt[1]}"
echo -ne "\033[33m [2] > " && msg -azu "CREAR USUARIO TEMPORAL"
echo -ne "\033[33m [3] > " && msg -azu "${txt[2]}"
echo -ne "\033[33m [4] > " && msg -azu "${txt[3]}"
echo -ne "\033[33m [5] > " && msg -azu "${txt[13]}"
echo -ne "\033[33m [6] > " && msg -azu "${txt[4]}"
echo -ne "\033[33m [7] > " && msg -azu "${txt[5]}"
echo -ne "\033[33m [8] > " && msg -azu "${txt[6]}"
echo -ne "\033[33m [9] > " && msg -azu "${txt[9]}"
echo -ne "\033[33m [10] > " && msg -azu "${txt[12]}"
echo -ne "\033[33m [11] > " && msg -azu "${txt[10]} ${verificar}"
echo -ne "\033[33m [0] > " && msg -bra "${txt[11]}"
msg -bar
unset selection
while [[ ${selection} != @(0|[1-9]|10|11) ]]; do
echo -ne "\033[1;37m${txt[8]}: " && read selection
tput cuu1 && tput dl1
done
case ${selection} in
1)new_user;;
2)user_demo;;
3)remove_user;;
4)edit_user;;
5)renew_user;;
6)detail_user;;
7)monit_user;;
8)rm_vencidos;;
9)backup_fun;;
10)baner_fun;;
11)verif_funx;;
esac